import = ["/Users/steveyko/.config/alacritty/themes/themes/solarized_dark.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.normal]
family = "MesloLGS Nerd Font"

[font.offset]
y = 5

[window]
dynamic_title = true

[window.dimensions]
columns = 120
lines = 45
